# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

virtualenv:
  system_site_packages: true

before_install:
 - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
 - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
 - sudo apt-get install -qq python-numpy python-scipy

install: pip install -r requirements_travis.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test