# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install: pip install --use-mirrors -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test