# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev

install:
  - pip install -r requirements.txt

script: nosetests