# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.2"
  - "2.7"

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt

install:
 - sudo apt-get install gfortran libopenblas-dev liblapack-dev
 - pip install -r requirements.txt
 - python setup.py install

script: nosetests