# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"

notifications:
  email: false

virtualenv:
  system_site_packages: true

before_install: pip install numpy scipy

install: python setup.py install

script: nosetests